# Generated by Django 4.1 on 2023-06-18 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('about', models.TimeField()),
                ('position', models.CharField(choices=[('manager', 'manager'), ('TL', 'TL'), ('Senior manger', 'Senior manger')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
