# Generated by Django 4.1 on 2023-06-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='about',
            field=models.TextField(),
        ),
    ]
